# hash:sha256:268c6d4abe0692df540b1fee3fdf7f9f8f11393467b05bc66d564914d045cef5
FROM registry.codeocean.com/codeocean/miniconda3:4.8.2-python3.8-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    matplotlib \
    numpy
